In [2]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [3]:
#2. Print the NUMPY version and the configuration.
print(np.__version__)

print(np.show_config())

1.16.4
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/alona/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/alona/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/alona/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/alona/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/alona/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/alona/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/alona/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/alona/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/alona/anaconda3/lib']
    defi

In [4]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?
a = np.random.random((2,3,5))
print(a)
print('*')
#a1 = np.empty((2,3,5))
#print(a1)
#4. Print a.

[[[0.63604625 0.81875251 0.733337   0.53091384 0.43777384]
  [0.49462542 0.95147902 0.45959746 0.7066071  0.96431515]
  [0.08683356 0.713782   0.31767233 0.5013141  0.9333307 ]]

 [[0.98040879 0.31807951 0.12941284 0.02018735 0.89063815]
  [0.87481968 0.29610711 0.5316447  0.63546952 0.55006683]
  [0.12894758 0.30881331 0.03957985 0.49405887 0.5742017 ]]]
*


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.ones((5,2,3))
#6. Print b.
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
#7. Do a and b have the same size? How do you prove that in Python code?
print(a.size)
print(b.size)

30
30


In [34]:
#8. Are you able to add a and b? Why or why not?
'''a and b have different lengths and widths, so its impossible to concatenate this arrays'''

In [7]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array 
#to varialbe "c".
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [8]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
d = np.vstack([a, c])
print(d)
#Now the dimensions of arrays are the same

[[[0.63604625 0.81875251 0.733337   0.53091384 0.43777384]
  [0.49462542 0.95147902 0.45959746 0.7066071  0.96431515]
  [0.08683356 0.713782   0.31767233 0.5013141  0.9333307 ]]

 [[0.98040879 0.31807951 0.12941284 0.02018735 0.89063815]
  [0.87481968 0.29610711 0.5316447  0.63546952 0.55006683]
  [0.12894758 0.30881331 0.03957985 0.49405887 0.5742017 ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]]


In [9]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
print("Array a:")
print(a)
print("Array d:")
print(d)
#The relation is about number of rows in each array, array d contains array a.
#The difference is about the size of arrays

Array a:
[[[0.63604625 0.81875251 0.733337   0.53091384 0.43777384]
  [0.49462542 0.95147902 0.45959746 0.7066071  0.96431515]
  [0.08683356 0.713782   0.31767233 0.5013141  0.9333307 ]]

 [[0.98040879 0.31807951 0.12941284 0.02018735 0.89063815]
  [0.87481968 0.29610711 0.5316447  0.63546952 0.55006683]
  [0.12894758 0.30881331 0.03957985 0.49405887 0.5742017 ]]]
Array d:
[[[0.63604625 0.81875251 0.733337   0.53091384 0.43777384]
  [0.49462542 0.95147902 0.45959746 0.7066071  0.96431515]
  [0.08683356 0.713782   0.31767233 0.5013141  0.9333307 ]]

 [[0.98040879 0.31807951 0.12941284 0.02018735 0.89063815]
  [0.87481968 0.29610711 0.5316447  0.63546952 0.55006683]
  [0.12894758 0.30881331 0.03957985 0.49405887 0.5742017 ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1. 

In [10]:
#12. Multiply a and c. Assign the result to e.
e = np.multiply(a, c)
print("A:", a)
print("C:", c)
print("E:", e)

A: [[[0.63604625 0.81875251 0.733337   0.53091384 0.43777384]
  [0.49462542 0.95147902 0.45959746 0.7066071  0.96431515]
  [0.08683356 0.713782   0.31767233 0.5013141  0.9333307 ]]

 [[0.98040879 0.31807951 0.12941284 0.02018735 0.89063815]
  [0.87481968 0.29610711 0.5316447  0.63546952 0.55006683]
  [0.12894758 0.30881331 0.03957985 0.49405887 0.5742017 ]]]
C: [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
E: [[[0.63604625 0.81875251 0.733337   0.53091384 0.43777384]
  [0.49462542 0.95147902 0.45959746 0.7066071  0.96431515]
  [0.08683356 0.713782   0.31767233 0.5013141  0.9333307 ]]

 [[0.98040879 0.31807951 0.12941284 0.02018735 0.89063815]
  [0.87481968 0.29610711 0.5316447  0.63546952 0.55006683]
  [0.12894758 0.30881331 0.03957985 0.49405887 0.5742017 ]]]


In [11]:
#13. Does e equal to a? Why or why not?
print(a.size)
print(e.size)
#They are equal. Because multiplication for 1 don't give any changes

30
30


In [12]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"
#print(d)
d_max = np.max(d)
d_min = np.min(d)
#d_mean = np.mean(d)
print("d_max = ", d_max)
print("d_min = ", d_min)
summ = 0
elements = 0
for i in d:
    for j in i:
        for k in j:
            summ += k
            elements += 1
d_mean = summ / elements
print("d_mean = ", d_mean)

d_max =  1.0
d_min =  0.020187350709493845
d_mean =  0.767646934573487


In [13]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) 
#as d using `np.empty`.
f = np.empty((2,3,5))
print(f)
print("d", d)


[[[0.63604625 0.81875251 0.733337   0.53091384 0.43777384]
  [0.49462542 0.95147902 0.45959746 0.7066071  0.96431515]
  [0.08683356 0.713782   0.31767233 0.5013141  0.9333307 ]]

 [[0.98040879 0.31807951 0.12941284 0.02018735 0.89063815]
  [0.87481968 0.29610711 0.5316447  0.63546952 0.55006683]
  [0.12894758 0.30881331 0.03957985 0.49405887 0.5742017 ]]]
d [[[0.63604625 0.81875251 0.733337   0.53091384 0.43777384]
  [0.49462542 0.95147902 0.45959746 0.7066071  0.96431515]
  [0.08683356 0.713782   0.31767233 0.5013141  0.9333307 ]]

 [[0.98040879 0.31807951 0.12941284 0.02018735 0.89063815]
  [0.87481968 0.29610711 0.5316447  0.63546952 0.55006683]
  [0.12894758 0.30881331 0.03957985 0.49405887 0.5742017 ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.      

In [14]:
d[0][1][0]

0.4946254195126817

In [33]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the 
corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
print(d)
print("d_max = ", d_max)
print("d_min = ", d_min)
print("d_mean = ", d_mean)
print("---")
m_more_than_min = f > f_min 
m_mean = f >= f_mean
m_more_than_mean = f > f_mean
m_max = f == f_max
                
f_fin = 25 * m_more_than_min + 25 * m_mean + 25 * m_more_than_mean + 25 * m_max
print("\nOutput array: \n\n", f_fin)

[[[0.63604625 0.81875251 0.733337   0.53091384 0.43777384]
  [0.49462542 0.95147902 0.45959746 0.7066071  0.96431515]
  [0.08683356 0.713782   0.31767233 0.5013141  0.9333307 ]]

 [[0.98040879 0.31807951 0.12941284 0.02018735 0.89063815]
  [0.87481968 0.29610711 0.5316447  0.63546952 0.55006683]
  [0.12894758 0.30881331 0.03957985 0.49405887 0.5742017 ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]]
d_max =  1.0
d_min =  0.020187350709493845
d_mean =  0.767646934573487
---

Output array: 

 [[[ 75  75  75  75  25]
  [ 75  25  25  25  25]
  [ 25  25  25  75  25]]

 [[ 75  75  25  75  75]
  [ 75  75  25  75  75]
  [ 25  25   0 100  75]]]


In [35]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""
print(d)
print(f_fin)

[[[0.63604625 0.81875251 0.733337   0.53091384 0.43777384]
  [0.49462542 0.95147902 0.45959746 0.7066071  0.96431515]
  [0.08683356 0.713782   0.31767233 0.5013141  0.9333307 ]]

 [[0.98040879 0.31807951 0.12941284 0.02018735 0.89063815]
  [0.87481968 0.29610711 0.5316447  0.63546952 0.55006683]
  [0.12894758 0.30881331 0.03957985 0.49405887 0.5742017 ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]

 [[1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]
  [1.         1.         1.         1.         1.        ]]]
[[[ 75  75  75  75  25]
  [ 75  25  25  25  25]
  [ 25  25  25  75  25]]

 [[ 75  75  25  75  75]
  [ 75  75  25  75  75]
  [ 25  25   0 100  75]]]


In [27]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

2


'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'

In [40]:
import numpy as np

np_arr = np.ones((2,5), dtype = int)
print(np_arr)
np_arr.size
np_arr.shape

[[1 1 1 1 1]
 [1 1 1 1 1]]


(2, 5)